### PR TITLE
Add dark theme for the dashboard

### PR DESCRIPTION
**Pull request by Brouilles**
See https://github.com/edandersen/core-admin/issues/29

### CODE REVIEW

**Comment by edandersen** [comment]
Could I get a screenshot before merging? :-D

**Comment by Brouilles** [comment]
Available in the Issue :)

147594007-99744eae-494e-4a70-9b91-924d2b1de398

**Comment by Brouilles** [comment]
image
image

**Comment by edandersen** [comment]
Thank you!

**Comment by edandersen** [comment]
Thanks!

**Pull request merged**
