### PR TITLE
Support all property types in grid

### PR DESCRIPTION
**Pull request by danroot**
Was still missing support for double and double? properties so I took a stab at making it to work for _any_ property type.

### CODE REVIEW

**Comment by edandersen** [comment]
🤯

Been trying to do this for two years. Legend.

**Comment by danroot** [comment]
@edandersen Any issues with this PR that I can address?  I'm pushing out an app for a client and would love to have a release with this in it, assuming it doesn't break anything for you.

**Comment by edandersen** [comment]
I haven't got round to testing it yet, hopefully this week.

**Comment by edandersen** [comment]
Merged, going out in 2.6.3 :-)

**Pull request merged**
